### ISSUE TITLE
Can you give some explanation?

### ISSUE THREAD

**Issue by devsteppe9** [FlySkyBear/vue-stomp#1]
Hello @FlySkyBear  I'am developing Spring with vue.js and I want to using your vue-stomp. So i have problem using your plugin. Can you give me some explanation or some example about how do i connect back-end service and how do id subscribe and how can i pass Authorization header?

**Comment by devsteppe9** [comment]
This is my plain JS example
```javascript
function connect() {
    var socket = new SockJS('http://localhost:8081/gs-guide-websocket');
    stompClient = Stomp.over(socket);
    stompClient.connect({}, function (frame) {
        setConnected(true);
        console.log('Connected: ' + frame);
        stompClient.subscribe('http://localhost:8081/signal/topic/greetings', function (greeting) {
            showGreeting(JSON.parse(greeting.body).content);
        });
    });
}
```

**Comment by FlySkyBear** [comment]
The end point is not need to set the http ' s head eg :"topic/user"

**Comment by devsteppe9** [comment]
The above code is just plain JS example not your plugin, can you give me example souce code?

**Comment by Ivikassingh** [comment]
how we can use this with rabbitmq

**Comment by FlySkyBear** [comment]
rabbitmq + stomp plugin is supported.
