### ISSUE TITLE
InvalidStateError: The connection has not been established yet

### ISSUE THREAD

**Issue by ShawshankLin** [FlySkyBear/vue-stomp#2]
![qq 20180225134037](https://user-images.githubusercontent.com/16248686/36638485-7f37be82-1a31-11e8-9fb2-5c8fbcf7fc90.png)

**Comment by ShawshankLin** [comment]
有时候会刷新后就会报这个错，，是什么原因呢？

**Comment by ShawshankLin** [comment]
这个项目现在还有维护吗？

**Comment by FlySkyBear** [comment]
你具体的页面结构不是很清楚，根据错误推测应该是没有建立连接就在发送数据，最好在发送数据前判定是否已经连接，或者给连接一定的时间准备。
